{
  lib,
  pkgs,
  ...
}: let
  # Script that auto-detects k10temp and Octo hwmon paths at boot,
  # then writes /etc/fancontrol with the correct device references.
  fancontrolSetup = pkgs.writeShellScript "fancontrol-setup" ''
        set -euo pipefail

        # Find k10temp (CPU temperature sensor)
        K10TEMP_HWMON=""
        for hwmon in /sys/class/hwmon/hwmon*; do
          if [ -f "$hwmon/name" ] && [ "$(cat "$hwmon/name")" = "k10temp" ]; then
            K10TEMP_HWMON=$(basename "$hwmon")
            break
          fi
        done

        # Find Octo (fan controller)
        OCTO_HWMON=""
        for hwmon in /sys/class/hwmon/hwmon*; do
          if [ -f "$hwmon/name" ] && [ "$(cat "$hwmon/name")" = "octo" ]; then
            OCTO_HWMON=$(basename "$hwmon")
            break
          fi
        done

        if [ -z "$K10TEMP_HWMON" ] || [ -z "$OCTO_HWMON" ]; then
          echo "fancontrol-setup: k10temp or Octo not found, skipping"
          exit 0
        fi

        K10TEMP_DEVPATH=$(readlink -f "/sys/class/hwmon/$K10TEMP_HWMON" | sed 's|/sys/||' | sed "s|/hwmon/$K10TEMP_HWMON||")
        OCTO_DEVPATH=$(readlink -f "/sys/class/hwmon/$OCTO_HWMON" | sed 's|/sys/||' | sed "s|/hwmon/$OCTO_HWMON||")

        cat > /etc/fancontrol <<EOF
    INTERVAL=2
    AVERAGE=$OCTO_HWMON/pwm1=5 $OCTO_HWMON/pwm2=5 $OCTO_HWMON/pwm3=5 $OCTO_HWMON/pwm4=5 $OCTO_HWMON/pwm5=5 $OCTO_HWMON/pwm6=5
    DEVPATH=$K10TEMP_HWMON=$K10TEMP_DEVPATH $OCTO_HWMON=$OCTO_DEVPATH
    DEVNAME=$K10TEMP_HWMON=k10temp $OCTO_HWMON=octo
    FCTEMPS=$OCTO_HWMON/pwm1=$K10TEMP_HWMON/temp1_input $OCTO_HWMON/pwm2=$K10TEMP_HWMON/temp1_input $OCTO_HWMON/pwm3=$K10TEMP_HWMON/temp1_input $OCTO_HWMON/pwm4=$K10TEMP_HWMON/temp1_input $OCTO_HWMON/pwm5=$K10TEMP_HWMON/temp1_input $OCTO_HWMON/pwm6=$K10TEMP_HWMON/temp1_input
    FCFANS=$OCTO_HWMON/pwm1=$OCTO_HWMON/fan1_input $OCTO_HWMON/pwm2=$OCTO_HWMON/fan2_input $OCTO_HWMON/pwm3=$OCTO_HWMON/fan3_input $OCTO_HWMON/pwm4=$OCTO_HWMON/fan4_input $OCTO_HWMON/pwm5=$OCTO_HWMON/fan5_input $OCTO_HWMON/pwm6=$OCTO_HWMON/fan6_input
    MINTEMP=$OCTO_HWMON/pwm1=50 $OCTO_HWMON/pwm2=50 $OCTO_HWMON/pwm3=50 $OCTO_HWMON/pwm4=50 $OCTO_HWMON/pwm5=50 $OCTO_HWMON/pwm6=50
    MAXTEMP=$OCTO_HWMON/pwm1=85 $OCTO_HWMON/pwm2=85 $OCTO_HWMON/pwm3=85 $OCTO_HWMON/pwm4=85 $OCTO_HWMON/pwm5=85 $OCTO_HWMON/pwm6=85
    MINSTART=$OCTO_HWMON/pwm1=38 $OCTO_HWMON/pwm2=38 $OCTO_HWMON/pwm3=38 $OCTO_HWMON/pwm4=50 $OCTO_HWMON/pwm5=50 $OCTO_HWMON/pwm6=50
    MINSTOP=$OCTO_HWMON/pwm1=38 $OCTO_HWMON/pwm2=38 $OCTO_HWMON/pwm3=38 $OCTO_HWMON/pwm4=50 $OCTO_HWMON/pwm5=50 $OCTO_HWMON/pwm6=50
    MINPWM=$OCTO_HWMON/pwm1=38 $OCTO_HWMON/pwm2=38 $OCTO_HWMON/pwm3=38 $OCTO_HWMON/pwm4=50 $OCTO_HWMON/pwm5=50 $OCTO_HWMON/pwm6=50
    MAXPWM=$OCTO_HWMON/pwm1=230 $OCTO_HWMON/pwm2=230 $OCTO_HWMON/pwm3=230 $OCTO_HWMON/pwm4=255 $OCTO_HWMON/pwm5=255 $OCTO_HWMON/pwm6=255
    EOF

        echo "fancontrol-setup: wrote /etc/fancontrol (k10temp=$K10TEMP_HWMON, octo=$OCTO_HWMON)"
  '';
in {
  # Aquacomputer Octo kernel driver
  boot.kernelModules = ["aquacomputer_d5next"];

  # Auto-detect hwmon paths and write /etc/fancontrol before fancontrol starts
  systemd.services.fancontrol-setup = {
    description = "Auto-detect Octo hwmon paths and generate /etc/fancontrol";
    wantedBy = ["multi-user.target"];
    before = ["fancontrol.service"];
    after = ["systemd-modules-load.service"];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${fancontrolSetup}";
    };
  };

  # fancontrol reads /etc/fancontrol generated by the setup service above
  #
  # Channel mapping (Aquacomputer Octo):
  #   1 = Top exhaust (rear)      3 = Rear exhaust
  #   2 = Top exhaust (front)     4 = Front intake (bottom)
  #   5 = Front intake (top)      6 = Front intake (middle)
  #
  # Fan curves (quiet profile, AVERAGE=5 for smoothing):
  #   Exhaust (1-3): <50C -> 15% | 67.5C -> 50% | 85C -> 90%
  #   Intake  (4-6): <50C -> 20% | 67.5C -> 55% | 85C -> 100%
  #   Intake runs higher than exhaust for positive pressure
  systemd.services.fancontrol = {
    description = "Fan control with temperature-based curves";
    wantedBy = ["multi-user.target"];
    after = ["fancontrol-setup.service"];
    requires = ["fancontrol-setup.service"];
    serviceConfig = {
      Restart = "on-failure";
      ExecStart = "${lib.getExe' pkgs.lm_sensors "fancontrol"} /etc/fancontrol";
    };
  };

  # Restart fancontrol after resume from sleep
  powerManagement.resumeCommands = ''
    systemctl restart fancontrol-setup.service
    systemctl restart fancontrol.service
  '';
}
