# focus window color (border)
general {
    col.active_border = rgb(e20342)
    col.inactive_border = rgb(2a153c)
}

# dims inactive windows and around active windows
decoration {
    dim_special = 0.4
    dim_inactive = true
    dim_strength = 0.4
}
