# Hyprland compositor -- Nix wiring, Lua config deployment, sub-component imports.
# The actual WM config lives in config/*.lua as pure Lua files.
# This file handles: enable/package/systemd, session vars, UWSM, XDG portal,
# xdg.configFile deployments, activation hooks, and theme hook registration.
#
# To swap a sub-component (e.g. rofi -> fuzzel), change the import below
# and update the corresponding defaults in this let block.
{
  config,
  lib,
  pkgs,
  host,
  ...
}: let
  themeLib = import ../../../lib/theme.nix {inherit pkgs config;};
  inherit (themeLib) kernixPath;
  monitors = host.desktop.monitors;
  primaryMonitor = lib.findFirst (m: m.primary) (builtins.head monitors) monitors;
  layout = host.desktop.hyprland.layout;
  tvOutput = host.desktop.hyprland.tvOutput;
  hdr = host.desktop.hyprland.hdr;
  hasTv = tvOutput != "";
  terminal = host.terminal;

  # Terminal metadata -- maps terminal name to Wayland app-id and exec flag.
  terminalMeta = {
    ghostty = {
      class = "com.mitchellh.ghostty";
      exec = "-e";
    };
  };
  termMeta =
    terminalMeta.${
      terminal
    } or {
      class = terminal;
      exec = "-e";
    };

  # ── Sub-component defaults ──
  # These are the commands each sub-component provides.
  # Swapping a component means changing the import AND these values.
  launcher = {
    run = "rofi -show drun";
    clipboard = ''cliphist list | rofi -dmenu -p 'Clipboard' | cliphist decode | wl-copy'';
    audio = "rofi-audio-select";
    power = "power-menu";
    theme = "kernix-rofi-theme-select";
    wallpaper = "kernix-rofi-wallpaper-select";
  };
  bar.start = "waybar";
  notifications.start = "mako";

  # Generate hl.monitor() calls from config.monitors.
  # On desktop, the primary monitor gets 10-bit wide gamut output
  # (Samsung Odyssey G95NC -> XBGR2101010). Using "wide" instead of "hdr"
  # because Hyprland lacks SDR-to-HDR tone mapping -- "hdr" makes desktop
  # content muddy. Games can still request HDR per-window via DXVK_HDR=1.
  monitorLines = builtins.concatStringsSep "\n" (map (
      m: let
        extraFields = lib.optionalString (hdr && m.primary) '', bitdepth = 10, cm = "wide"'';
      in ''hl.monitor({ output = "${m.name}", mode = "${m.resolution}", position = "${m.position}", scale = ${toString m.scale}${extraFields} })''
    )
    monitors);

  # Nix-templated entry point -- injects dynamic values as Lua globals,
  # then requires all sub-config files.
  hyprlandEntryPoint = ''
    -- Hyprland Lua configuration (generated by Nix)
    -- Do not edit directly -- modify the source .lua files in the kernix repo.

    -- Nix-injected globals
    TERMINAL = "${terminal}"
    TERMINAL_CLASS = "${termMeta.class}"
    TERMINAL_EXEC = "${termMeta.exec}"
    HAS_TV = ${lib.boolToString hasTv}
    TV_OUTPUT = "${tvOutput}"
    LAYOUT = "${layout}"
    PRIMARY_MONITOR = "${primaryMonitor.name}"
    LAUNCHER_RUN = "${launcher.run}"
    LAUNCHER_CLIPBOARD = "${launcher.clipboard}"
    LAUNCHER_AUDIO = "${launcher.audio}"
    LAUNCHER_POWER = "${launcher.power}"
    LAUNCHER_THEME = "${launcher.theme}"
    LAUNCHER_WALLPAPER = "${launcher.wallpaper}"
    BAR_START = "${bar.start}"
    NOTIFICATIONS_START = "${notifications.start}"

    -- Environment variables
    hl.env("KERNIX_PATH", "${kernixPath}")
    ${lib.optionalString hasTv ''hl.env("SSH_AUTH_SOCK", os.getenv("HOME") .. "/.bitwarden-ssh-agent.sock")''}

    -- Monitors (from config.monitors)
    ${monitorLines}

    -- Disable TV output (used exclusively by gamescope on TTY3)
    -- Without this, Hyprland auto-configures any detected monitor.
    ${lib.optionalString (tvOutput != "") ''hl.monitor({ output = "${tvOutput}", disabled = true })''}

    -- Cursor default monitor
    ${lib.optionalString (primaryMonitor.name != "") ''hl.config({ cursor = { default_monitor = "${primaryMonitor.name}" } })''}

    -- Sub-configs (each require() gets its own error scope)
    require("appearance")
    require("animations")
    require("input")
    require("layout")
    require("rules")
    require("binds")
    require("autostart")

    -- Theme (loaded last, overrides appearance defaults)
    local themeFile = os.getenv("HOME") .. "/.config/hypr/active-theme.lua"
    local f = io.open(themeFile, "r")
    if f then
      f:close()
      dofile(themeFile)
    end
  '';
in {
  imports = [
    ./bar/waybar
    ./launcher/rofi
    ./notifications/mako
    ./lock.nix
    ./idle.nix
  ];

  config = lib.mkIf host.desktop.enable {
    kernix.theme.hooks = ["hyprland"];

    # ── Wayland packages ──
    home.packages = with pkgs; [
      swaybg
      qt5.qtwayland
      qt6.qtwayland
      hyprland-qtutils
      wlr-randr
      wlogout

      # Wallpaper management (uses swaybg, called from keybinds)
      (writeShellApplication {
        name = "kernix-wallpaper-set";
        runtimeInputs = [swaybg coreutils findutils procps];
        text = ''
          export KERNIX_PATH="${kernixPath}"
          ${builtins.readFile ../../theme/scripts/kernix-wallpaper-set.sh}
        '';
      })
      (writeShellApplication {
        name = "kernix-wallpaper-next";
        runtimeInputs = [swaybg coreutils findutils procps libnotify];
        text = ''
          export KERNIX_PATH="${kernixPath}"
          ${builtins.readFile ../../theme/scripts/kernix-wallpaper-next.sh}
        '';
      })
    ];

    # ── Wayland session variables ──
    home.sessionVariables =
      {
        NIXOS_OZONE_WL = "1";
        XDG_SESSION_TYPE = "wayland";
        QT_QPA_PLATFORM = "wayland";
        QT_WAYLAND_DISABLE_WINDOWDECORATION = "1";
        QT_AUTO_SCREEN_SCALE_FACTOR = "1";
        MOZ_ENABLE_WAYLAND = "1";
        CLUTTER_BACKEND = "wayland";
        ELECTRON_OZONE_PLATFORM_HINT = "auto";
        _JAVA_AWT_WM_NONREPARENTING = "1";
      }
      // lib.optionalAttrs hdr {
        # HDR: tell DXVK/VKD3D and Vulkan WSI to use HDR output.
        # Games need these to output HDR to the compositor.
        DXVK_HDR = "1";
        ENABLE_HDR_WSI = "1";
      };

    # ── UWSM auto-start (TTY1 login only) ──
    # Only start Hyprland on TTY1. TTY3 is reserved for gamescope couch mode.
    programs.zsh.initContent = lib.mkOrder 100 ''
      if [[ "$(tty)" == "/dev/tty1" && -z "$DISPLAY" && -z "$WAYLAND_DISPLAY" ]] && uwsm check may-start 2>/dev/null; then
          exec uwsm start hyprland-uwsm.desktop
      fi
    '';

    # XDG portals are configured at the system level in system/desktop/hyprland.nix

    # ── Deploy Lua config files ──
    xdg.configFile = {
      "hypr/hyprland.lua".text = hyprlandEntryPoint;
      "hypr/appearance.lua".source = ./config/appearance.lua;
      "hypr/animations.lua".source = ./config/animations.lua;
      "hypr/input.lua".source = ./config/input.lua;
      "hypr/layout.lua".source = ./config/layout.lua;
      "hypr/rules.lua".source = ./config/rules.lua;
      "hypr/binds.lua".source = ./config/binds.lua;
      "hypr/autostart.lua".source = ./config/autostart.lua;
    };

    # ── Activation hooks ──
    home.activation.hyprlandThemeStubs = config.lib.dag.entryAfter ["linkGeneration"] ''
      mkdir -p "$HOME/.config/hypr/wallpapers"
      [ -e "$HOME/.config/hypr/active-theme.lua" ] || printf '-- no theme loaded yet\n' > "$HOME/.config/hypr/active-theme.lua"
    '';

    home.activation.hyprlandReload = lib.hm.dag.entryAfter ["linkGeneration"] ''
      if command -v hyprctl &>/dev/null && hyprctl monitors &>/dev/null 2>&1; then
        hyprctl reload &>/dev/null || true
      fi
    '';
  };
}
